version: "3.9"
networks:
    km-app:

services:
    nginx:
        image: nginx:stable
        container_name: nginx_km_app
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www:delegated
            - ./vhost.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - mysql
        networks:
            - km-app
    mysql:
        image: mysql:8
        container_name: mysql_km_app
        restart: unless-stopped
        tty: true
        ports:
            - "3308:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - km-app
        volumes:
            - mysql_data:/var/lib/mysql
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: php_km_app
        working_dir: /var/www
        volumes:
            - ./:/var/www:delegated
            - ./vendor:/var/www/vendor:cached
        networks:
            - km-app
volumes:
    mysql_data:
